package ru.shubert.jobportal.strategy;

import org.hibernate.cfg.EJB3NamingStrategy;

import java.util.Locale;

/**
 * Custom naming strategy for tables, columns and other DDL values. 
 * Best thing it's excludes any keywords from resulting sql queryes in autogenerated schemes.
 * {@link org.hibernate.cfg.EJB3NamingStrategy} was choosed as it's strippes out fqn from columns 
 *
 */

public class CustomNamingStrategy extends EJB3NamingStrategy{
    private static String TABLE_PREFIX = "F_";
    private static Locale NAME_LOCALE = Locale.ENGLISH;

    @Override
    public String classToTableName(String className) {
        final String value = super.classToTableName(className).toUpperCase(NAME_LOCALE);
        return TABLE_PREFIX.concat(value);
    }

    @Override
    public String propertyToColumnName(String propertyName) {
        final String value = super.propertyToColumnName(propertyName);
        return value.toUpperCase(NAME_LOCALE);
    }

    @Override
    public String tableName(String tableName) {
        final String value = super.tableName(tableName);
        return TABLE_PREFIX.concat(value.toUpperCase(NAME_LOCALE));
    }

    @Override
    public String columnName(String columnName) {
        final String value = super.columnName(columnName);
        return value.toUpperCase(NAME_LOCALE);
    }


}
